on:
    push:
        branches:
            - main

permissions:
    issues: write
    contents: write
    pull-requests: write

name: release-please

jobs:
    release-please:
        runs-on: ubuntu-latest
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  release-type: go
            - name: "Check if release created"
              if: ${{ steps.release.outputs.release_created }}
              run: echo "Release was created!"
            - name: "Check if release created"
              if: ${{ !steps.release.outputs.release_created }}
              run: echo "Release was not created!"
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        needs: release-please
        if: ${{ needs.release-please.outputs.release_created }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: go.mod

            - name: Install dependencies
              run: go mod download

            - name: Build
              shell: bash
              run: |
                  ARCH=$(go env GOARCH)
                  OS=$(go env GOOS)
                  BUILD_DIR=build/${OS}/${ARCH}

                  mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR}
                  for cmd in ../../../cmd/*/; do
                      cmd_name=$(basename "$cmd")
                      echo "Building ${cmd_name} for ${ARCH}-${OS}"

                      go build ${cmd}
                  done

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-${{ matrix.os }}
                  path: build/**/*

    release:
        name: Create release
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  merge-multiple: true
                  path: ./build

            - name: Archive build artifacts
              run: |
                  mkdir dist

                  for system_dir in ./build/*/; do
                      system=$(basename "$system_dir" | tr '[:upper:]' '[:lower:]')

                      for platform_dir in ${system_dir}/*/; do
                          arch=$(basename "$platform_dir" | tr '[:upper:]' '[:lower:]')

                          platform=${arch}-${system}
                          echo "Release platform: ${platform}"

                          output_file="./dist/app-${platform}"
                          case "$system" in
                              *win*)
                                  zip -jr "${output_file}.zip" "$platform_dir"
                                  ;;
                              *linux*)
                                  cd ${platform_dir} && tar -vczf "../../../${output_file}.tar.gz" * && cd -
                                  ;;
                              *)
                                  echo "Unknown platform: ${platform}"
                                  exit 1
                                  ;;
                          esac
                      done
                  done

            - name: Upload release
              uses: softprops/action-gh-release@v2
              with:
                  generate_release_notes: true
                  files: ./dist/**/*
